-- Schema SQL pour l'application de gestion des soutenances de thèse
--creez un schema pour organiser les tables de l'application
CREATE SCHEMA jury;

--create a table for fields of study

CREATE TABLE jury.filiere (
    id_filiere integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_filiere varchar(10) UNIQUE NOT NULL,
    libelle varchar(100) NOT NULL
);

--create a table to store the rooms where the jury sessions will take place, including the name, capacity, building, and available equipment

CREATE TABLE jury.salle (
    id_salle integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_salle character varying(50) NOT NULL,
    capacite integer NOT NULL,
    batiment character varying(50),
    equipements text,
    CONSTRAINT salle_capacite_check CHECK ((capacite > 0)),
    CONSTRAINT salle_nom_salle_key UNIQUE (nom_salle)
);
--create a table to store the sessions of the jury, including the label, academic year, start date, end date, and status (planned, ongoing, closed)

CREATE TABLE jury.session (
    id_session integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle character varying(150) NOT NULL,
    annee_academique character varying(10) NOT NULL,
    date_debut date NOT NULL,
    date_fin date NOT NULL,
    statut character varying(20) DEFAULT 'planifiée'::character varying NOT NULL,
    CONSTRAINT chk_dates CHECK ((date_fin >= date_debut)),
    CONSTRAINT session_statut_check CHECK (((statut)::text = ANY ((ARRAY['planifiée'::character varying, 'en_cours'::character varying, 'cloturée'::character varying])::text[])))
);
--create a table to store the teachers, including their matricule, name, grade, specialty, email, phone number, and status (active or inactive)

CREATE TABLE jury.enseignant (
    id_enseignant integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricule character varying(20) NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    grade character varying(50),
    specialite character varying(100),
    email character varying(150),
    telephone character varying(20),
    statut character varying(30) DEFAULT 'actif'::character varying NOT NULL,
    CONSTRAINT enseignant_statut_check CHECK (((statut)::text = ANY ((ARRAY['actif'::character varying, 'inactif'::character varying, 'congé'::character varying])::text[]))),
    CONSTRAINT enseignant_email_key UNIQUE (email),
    CONSTRAINT enseignant_matricule_key UNIQUE (matricule)
);

--create a table to store the students, including their matricule, name, date of birth, email, phone number, and the ID of their field of study (filiere)

CREATE TABLE jury.etudiant (
    id_etudiant integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricule character varying(20) NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    date_naissance date,
    email character varying(150),
    telephone character varying(20),
    id_filiere integer NOT NULL,
    CONSTRAINT etudiant_email_key UNIQUE (email),
    CONSTRAINT etudiant_matricule_key UNIQUE (matricule),
    CONSTRAINT etudiant_id_filiere_fkey FOREIGN KEY (id_filiere) REFERENCES jury.filiere (id_filiere)
);

--create a table to store the reports submitted by students for their thesis defense, including the title, summary, file URL, submission date, student ID, session ID, and status of the report

CREATE TABLE jury.rapport (
    id_rapport integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre character varying(255) NOT NULL,
    resume text,
    fichier_url character varying(300),
    date_depot timestamp without time zone DEFAULT now() NOT NULL,
    id_etudiant integer NOT NULL,
    id_session integer NOT NULL,
    statut character varying(30) DEFAULT 'déposé'::character varying NOT NULL,
    CONSTRAINT rapport_statut_check CHECK (((statut)::text = ANY ((ARRAY['déposé'::character varying, 'validé'::character varying, 'soutenu'::character varying])::text[]))),
    CONSTRAINT rapport_id_etudiant_fkey FOREIGN KEY (id_etudiant) REFERENCES jury.etudiant (id_etudiant),
    CONSTRAINT rapport_id_session_fkey FOREIGN KEY (id_session) REFERENCES jury.session (id_session)
);
--creez une table pour stocker les disponibilités des enseignants pour les sessions de soutenance
CREATE TABLE jury.disponibilite (
    id_disponibilite integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_enseignant integer NOT NULL,
    id_session integer NOT NULL,
    date_debut timestamp without time zone NOT NULL,
    date_fin timestamp without time zone NOT NULL,
    CONSTRAINT chk_dispo_dates CHECK ((date_fin > date_debut)),
    CONSTRAINT disponibilite_id_enseignant_fkey FOREIGN KEY (id_enseignant) REFERENCES jury.enseignant (id_enseignant),
    CONSTRAINT disponibilite_id_session_fkey FOREIGN KEY (id_session) REFERENCES jury.session (id_session)
);
--creer une table pour stocker le programme des soutenance

CREATE TABLE jury.programme (
    id_programme integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_session integer NOT NULL,
    id_rapport integer NOT NULL,
    id_salle integer NOT NULL,
    date_heure timestamp without time zone NOT NULL,
    duree_minutes integer DEFAULT 45 NOT NULL,
    statut character varying(30) DEFAULT 'proposé'::character varying NOT NULL,
    CONSTRAINT programme_duree_minutes_check CHECK ((duree_minutes > 0)),
    CONSTRAINT programme_statut_check CHECK (((statut)::text = ANY ((ARRAY['proposé'::character varying, 'validé'::character varying, 'annulé'::character varying, 'réalisé'::character varying])::text[]))),
    CONSTRAINT programme_id_salle_date_heure_key UNIQUE (id_salle, date_heure),
    CONSTRAINT programme_id_rapport_fkey FOREIGN KEY (id_rapport) REFERENCES jury.rapport (id_rapport),
    CONSTRAINT programme_id_salle_fkey FOREIGN KEY (id_salle) REFERENCES jury.salle (id_salle),
    CONSTRAINT programme_id_session_fkey FOREIGN KEY (id_session) REFERENCES jury.session (id_session)
);
--creez une table pour stocker la composition du jury pour chaque programme

CREATE TABLE jury.jury (
    id_jury integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_programme integer NOT NULL,
    id_enseignant integer NOT NULL,
    role_jury character varying(30) NOT NULL,
    present boolean DEFAULT false NOT NULL,
    CONSTRAINT jury_role_jury_check CHECK (((role_jury)::text = ANY ((ARRAY['président'::character varying, 'rapporteur'::character varying, 'examinateur'::character varying, 'directeur'::character varying])::text[]))),
    CONSTRAINT jury_id_programme_id_enseignant_key UNIQUE (id_programme, id_enseignant),
    CONSTRAINT jury_id_enseignant_fkey FOREIGN KEY (id_enseignant) REFERENCES jury.enseignant (id_enseignant),
    CONSTRAINT jury_id_programme_fkey FOREIGN KEY (id_programme) REFERENCES jury.programme (id_programme)
);
--creez une table pour stocker les résultats des délibérations du jury pour chaque programme, y compris la mention, la note, les observations et la date de délibération
CREATE TABLE jury.resultat (
    id_resultat integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_programme integer NOT NULL,
    mention character varying(30),
    note numeric(4,2),
    observation text,
    date_deliberation timestamp without time zone DEFAULT now() NOT NULL,
    enregistre_par integer,
    CONSTRAINT resultat_mention_check CHECK (((mention)::text = ANY ((ARRAY['très_bien'::character varying, 'bien'::character varying, 'assez_bien'::character varying, 'passable'::character varying, 'ajourné'::character varying])::text[]))),
    CONSTRAINT resultat_note_check CHECK (((note >= (0)::numeric) AND (note <= (20)::numeric))),
    CONSTRAINT resultat_id_programme_key UNIQUE (id_programme),
    CONSTRAINT resultat_enregistre_par_fkey FOREIGN KEY (enregistre_par) REFERENCES jury.enseignant (id_enseignant),
    CONSTRAINT resultat_id_programme_fkey FOREIGN KEY (id_programme) REFERENCES jury.programme (id_programme)
);
--creez une table pour stocker les validations des programmes par les enseignants, y compris le statut de validation (en attente, validé, refusé) pour chaque programme et chaque enseignant

CREATE TABLE jury.validation_programme (
    id_programme integer NOT NULL,
    id_enseignant integer NOT NULL,
    statut character varying(20) DEFAULT 'en_attente' NOT NULL,
    PRIMARY KEY (id_programme, id_enseignant),
    CONSTRAINT validation_id_programme_fkey FOREIGN KEY (id_programme) REFERENCES jury.programme (id_programme),
    CONSTRAINT validation_id_enseignant_fkey FOREIGN KEY (id_enseignant) REFERENCES jury.enseignant (id_enseignant)
);



--Creez une table pour stocker les utilisateurs de l'application, y compris leur email, mot de passe hashé, rôle (coordinateur, enseignant, admin) et l'ID de l'enseignant associé (le cas échéant)

CREATE TABLE jury.utilisateur (
    id_utilisateur integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(150) NOT NULL,
    mot_de_passe_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    id_enseignant integer,
    CONSTRAINT utilisateur_email_key UNIQUE (email),
    CONSTRAINT utilisateur_role_check CHECK (role IN ('etudiant', 'enseignant', 'admin')),
    CONSTRAINT utilisateur_id_enseignant_fkey FOREIGN KEY (id_enseignant) REFERENCES jury.enseignant (id_enseignant)
);

--
-- Creez une vue pour afficher le programme complet de chaque session de soutenance, y compris la date, l'heure, la durée, le nom de la salle, le nom de l'étudiant, le titre du rapport et le statut de la soutenance

CREATE VIEW jury.vue_programme_complet AS
 SELECT ps.id_programme,
    ss.libelle AS session,
    ss.annee_academique,
    ps.date_heure,
    ps.duree_minutes,
    s.nom_salle,
    s.batiment,
    e.matricule AS matricule_etudiant,
    (((e.nom)::text || ' '::text) || (e.prenom)::text) AS etudiant,
    r.titre AS titre_rapport,
    ps.statut AS statut_soutenance
   FROM ((((jury.programme ps
     JOIN jury.session ss ON ((ps.id_session = ss.id_session)))
     JOIN jury.rapport r ON ((ps.id_rapport = r.id_rapport)))
     JOIN jury.etudiant e ON ((r.id_etudiant = e.id_etudiant)))
     JOIN jury.salle s ON ((ps.id_salle = s.id_salle)))
  ORDER BY ps.date_heure;

  --creez une vue pour afficher la composition du jury pour chaque programme, y compris le nom de l'étudiant, le titre du rapport, le nom et le grade de chaque membre du jury, ainsi que leur rôle et leur présence lors de la soutenance

CREATE VIEW jury.vue_composition_jury AS
 SELECT ps.id_programme,
    ps.date_heure,
    (((e_etud.nom)::text || ' '::text) || (e_etud.prenom)::text) AS etudiant,
    r.titre,
    (((ens.nom)::text || ' '::text) || (ens.prenom)::text) AS membre_jury,
    ens.grade,
    j.role_jury,
    j.present
   FROM ((((jury.jury j
     JOIN jury.programme ps ON ((j.id_programme = ps.id_programme)))
     JOIN jury.rapport r ON ((ps.id_rapport = r.id_rapport)))
     JOIN jury.etudiant e_etud ON ((r.id_etudiant = e_etud.id_etudiant)))
     JOIN jury.enseignant ens ON ((j.id_enseignant = ens.id_enseignant)))
  ORDER BY ps.date_heure, j.role_jury;

  --creez une vue pour afficher les résultats des délibérations du jury pour chaque programme, y compris la session, l'année académique, le matricule et le nom de l'étudiant, le titre du rapport, la note, la mention, les observations et la date de délibération

CREATE VIEW jury.vue_resultats AS
 SELECT ss.libelle AS session,
    ss.annee_academique,
    e.matricule,
    (((e.nom)::text || ' '::text) || (e.prenom)::text) AS etudiant,
    r.titre,
    rs.note,
    rs.mention,
    rs.observation,
    rs.date_deliberation
   FROM ((((jury.resultat rs
     JOIN jury.programme ps ON ((rs.id_programme = ps.id_programme)))
     JOIN jury.session ss ON ((ps.id_session = ss.id_session)))
     JOIN jury.rapport r ON ((ps.id_rapport = r.id_rapport)))
     JOIN jury.etudiant e ON ((r.id_etudiant = e.id_etudiant)))
  ORDER BY ss.date_debut, e.nom;

--creez des index pour optimiser les requêtes sur les tables les plus utilisées

CREATE INDEX idx_dispo_enseignant ON jury.disponibilite USING btree (id_enseignant);
CREATE INDEX idx_jury_enseignant ON jury.jury USING btree (id_enseignant);
CREATE INDEX idx_jury_programme ON jury.jury USING btree (id_programme);
CREATE INDEX idx_programme_date ON jury.programme USING btree (date_heure);
CREATE INDEX idx_programme_session ON jury.programme USING btree (id_session);
CREATE INDEX idx_rapport_etudiant ON jury.rapport USING btree (id_etudiant);
CREATE INDEX idx_rapport_session ON jury.rapport USING btree (id_session);
CREATE INDEX idx_validation_prog ON jury.validation_programme USING btree (id_programme);
